language: r
sudo: false
cache: packages
warnings_are_errors: false

matrix:
  include:
    - os: linux
      dist: xenial
      r: release
      env: 
        - DIST=xenial
        - AFTER_JOBS=true
    - os: linux
      dist: xenial
      r: devel
      env: 
        - DIST=xenial
        - AFTER_JOBS=false
    - os: linux
      dist: bionic
      r: release
      env: 
        - DIST=bionic
        - AFTER_JOBS=false
    - os: windows
      r: release
      env: 
        - DIST=windows
        - AFTER_JOBS=false
  allow_failures:
    - os: windows

env:
  global:
    - _R_CHECK_TESTS_NLINES_=0

r_packages:
  - covr
  - lintr
  - roxygen2
  - devtools

before_script:
  - export PKG_TARBALL=$(Rscript -e 'pkg <- devtools::as.package("."); cat(paste0(pkg$package,"_",pkg$version,".tar.gz"))')

script:
  - R CMD build .
  - R CMD check *tar.gz

after_script:
  - |
    if [[ "$AFTER_JOBS" == "true" ]] && [[ "$TRAVIS_EVENT_TYPE" == "push" ]]; then
      Rscript -e 'lintr::lint_package()'
    fi

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'roxygen2::roxygenise()'

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
  on:
    branch: master
    condition: "$AFTER_JOBS = true"
    type: push

notifications:
  email:
    on_success: change # default: change
    on_failure: change # default: always
