language: r
cache: packages

r:
  - oldrel
  - release

services:
  - docker

addons:
  apt:
    packages:
      - language-pack-nb

env:
  global:
    - _R_CHECK_TESTS_NLINES_=0

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - r-lib/pkgdown

before_install:
  - Rscript -e 'Sys.setlocale(category = "LC_ALL", locale = "no_NO.UTF-8")'
  - R CMD build .
  - docker build --build-arg GITHUB_PAT=${GITHUB_PAT} -t hnskde/qmongr .
  - rm qmongr_*.tar.gz
  - docker run -d -p 127.0.0.1:3838:3838 --name qmongr hnskde/qmongr
  - Rscript -e 'remotes::install_github("SKDE-Felles/qmongrdata", ref = "csv")'

after_success:
  - R CMD INSTALL $PKG_TARBALL
  - |
    if [[ "$TRAVIS_R_VERSION_STRING" == "release" ]] && [[ "$TRAVIS_EVENT_TYPE" == "push" ]]; then
      Rscript -e 'lintr::lint_package()'
      Rscript -e 'covr::codecov()'
    fi
  - rm -rf qmongr.Rcheck
  - Rscript -e 'pkgdown::build_site()'

deploy:
  # our site to gh_pages
  - provider: pages
    skip_cleanup: true
    token: $GH_TOKEN
    keep_history: false
    local_dir: docs
    on:
      branch: master
      condition: $TRAVIS_R_VERSION_STRING == "release"
  # our image to dockerhub
  - provider: script
    script: bash docker_push
    skip_cleanup: true
    on:
      # next two maybe to be replaced by: 'tags: true'
      branch: master
      condition: $TRAVIS_R_VERSION_STRING == "release"


