language: r
cache: packages

r:
  - oldrel
  - release
  - devel

services:
  - docker

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - r-lib/pkgdown

before_install:
  - R CMD build .
  - docker build --build-arg GITHUB_PAT=${GITHUB_PAT} -t hnskde/qmongr .
  - rm qmongr_*.tar.gz
  - docker run -d -p 127.0.0.1:3838:3838 --name qmongr hnskde/qmongr

after_success:
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'lintr::lint_package()'
  - rm -rf qmongr.Rcheck
  - Rscript -e 'covr::codecov()'

deploy:
  # our site to gh_pages
  - provider: script
    script: Rscript -e 'pkgdown::deploy_site_github()'
    skip_cleanup: true
    on:
      branch: travis_reboot
  # our image to dockerhub
  - provider: script
    script: bash docker_push
    skip_cleanup: true
    on:
      branch: master

