language: r
cache: packages

r:
  - oldrel
  - release
  - devel

services:
  - docker

env:
  global:
    - _R_CHECK_TESTS_NLINES_=0

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - r-lib/pkgdown

before_install:
  - R CMD build .
  - docker build --build-arg GITHUB_PAT=${GITHUB_PAT} -t hnskde/qmongr .
  - rm qmongr_*.tar.gz
  - docker run -d -p 127.0.0.1:3838:3838 --name qmongr hnskde/qmongr

after_success:
  - R CMD INSTALL $PKG_TARBALL
  - |
    if [[ "$TRAVIS_R_VERSION_STRING" == "release" ]]; then
      Rscript -e 'lintr::lint_package()'
      Rscript -e 'covr::codecov()'
      Rscript -e 'pkgdown::build_site()'
    fi
  - rm -rf qmongr.Rcheck

deploy:
  # our site to gh_pages
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: false
    local_dir: docs
    on:
      branch: master
      condition: $TRAVIS_R_VERSION_STRING == "release"
  # our image to dockerhub
  - provider: script
    script: bash docker_push
    skip_cleanup: true
    on:
      # next two maybe to be replaced by: 'tags: true'
      branch: master
      condition: $TRAVIS_R_VERSION_STRING == "release"


