language: r
cache: packages

matrix:
  include:
    - os: linux
      dist: xenial
      r: release
      env: 
        - DIST=xenial
        - AFTER_JOBS=true
    - os: linux
      dist: xenial
      r: devel
      env: 
        - DIST=xenial
        - AFTER_JOBS=false
    - os: linux
      dist: bionic
      r: release
      env: 
        - DIST=bionic
        - AFTER_JOBS=false

env:
  global:
    - _R_CHECK_TESTS_NLINES_=0

r_packages:
  - covr
  - lintr
  - roxygen2
  - devtools

before_script:
  - export PKG_TARBALL=$(Rscript -e 'pkg <- devtools::as.package("."); cat(paste0(pkg$package,"_",pkg$version,".tar.gz"))')

script:
  - R CMD build .
  - R CMD check --as-cran *tar.gz

after_script:
  - |
    if [[ "$AFTER_JOBS" == "true" ]] && [[ "$TRAVIS_EVENT_TYPE" == "push" ]]; then
      Rscript -e 'lintr::lint_package()'
    fi

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'roxygen2::roxygenise()'

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  # our site to gh_pages
  - provider: script
    script: Rscript -e 'pkgdown::deploy_site_github()'
    skip_cleanup: true
    on:
      branch: master
      condition: "$AFTER_JOBS = true"
      type: push
  # our image to dockerhub
  - provider: script
    script: docker_push
    on:
      branch: master

notifications:
  email:
    on_success: change # default: change
    on_failure: change # default: always
