language: r
cache: packages

r:
  - oldrel
  - release
  - devel

services:
  - docker

env:
  global:
    - _R_CHECK_TESTS_NLINES_=0

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - r-lib/pkgdown
  - rstudio/shiny

before_install:
  - R CMD build .
  - docker build --build-arg GITHUB_PAT=${GITHUB_PAT} -t hnskde/qmongr .
  - rm qmongr_*.tar.gz
  - docker run -d -p 127.0.0.1:3838:3838 --name qmongr hnskde/qmongr

before_script:
  - docker ps | grep -q qmongr
  - curl -IsSf 127.0.0.1:3838 > /dev/null

after_success:
  - R CMD INSTALL $PKG_TARBALL
  - |
    if [[ "$TRAVIS_R_VERSION_STRING" == "release" ]] && [[ "$TRAVIS_EVENT_TYPE" == "push" ]]; then
      Rscript -e 'lintr::lint_package()'
      Rscript -e 'covr::codecov()'
    fi
  - rm -rf qmongr.Rcheck
  - Rscript -e 'pkgdown::build_site()'

deploy:
  # our site to gh_pages
  - provider: pages
    skip_cleanup: true
    token: $GH_TOKEN
    keep_history: false
    local_dir: docs
    on:
      branch: master
      condition: $TRAVIS_R_VERSION_STRING == "release"
  # our image to dockerhub
  - provider: script
    script: bash docker_push
    skip_cleanup: true
    on:
      branch: master
      condition: $TRAVIS_R_VERSION_STRING == "release"


