#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

if [[ "$TRAVIS_TAG" == "true" ]]; then
  docker push hnskde/qmongr
fi

if [[ "$TRAVIS_BRANCH" == "master" ]]; then
  docker tag hnskde/qmongr hnskde/qmongr:test
  docker push hnskde/qmongr:test
fi
